---
- name: ensure system general packages are installed
  apt: pkg="{{ item }}" state=latest
  with_items:
    - thunderbird
    - deluge
    - filezilla
    - keepassx
  sudo: yes


- name: Download Dropbox
  shell: aria2c -c -x 10 -s {{ downloadThreads }} https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ vDropbox }}_amd64.deb chdir={{ downloadDir }} creates=dropbox_{{ vDropbox }}_amd64.deb

- name: Install Dropbox
  apt: deb={{ downloadDir }}/dropbox_{{ vDropbox }}_amd64.deb
  sudo: yes
