---
- name: Ubuntu Web Dev Machine
  hosts: 127.0.0.1
  connection: local
  vars:
    hostname: localhost
    downloadDir: /home/{{ ansible_ssh_user }}/Downloads-Ubuntu-Like-A-Pro
    installDir: /home/{{ ansible_ssh_user }}/Software
    apacheLocalhostDocumentRoot: /home/{{ ansible_ssh_user }}/www
    downloadThreads: 20
    installNvidiaDriver: "no"
    vPhpStorm: 8.0.1
    vPyCharm: 3.4.1
    vRubyMine: 7.0
    vODesk: 3.12.9
    vVagrant: 1.6.5
    vMySQLWB: 6.2.3-1ubu1404
    v0xDBE: 138.2222.2
    vRoboMongo: 0.8.4
    vDropbox: 1.6.2
    vRuby_rbenv: 2.1.5

  roles:
      - initial
      - system_essential
# Order of "initial" and "system_essentials" roles is important ! Keep it at the top.
      - ide
      - browser
      - system_general
      - web_dev_essential
      - web_dev_tools
#     - tracker    # uncomment to install oDesk and Elance trackers
      - media
      - tweak
