---
- name: Ubuntu Web Dev Machine
  hosts: 127.0.0.1
  connection: local
  vars:
    hostname: localhost
    downloadDir: /home/{{ ansible_ssh_user }}/Downloads-Ubuntu-Like-A-Pro
    installDir: /home/{{ ansible_ssh_user }}/Software
    apacheLocalhostDocumentRoot: /home/{{ ansible_ssh_user }}/www
    downloadThreads: 20
    installNvidiaDriver: "no"
    vPhpStorm: 10.0.1
    vPyCharm: 5.0.3
    vVagrant: 1.8.1
    vMySQLWB: 6.2.4-1ubu1404
    vDropbox: 1.6.2
    vRuby_rbenv: 2.2.0

  roles:
      - initial
      - system_essential
# Order of "initial" and "system_essentials" roles is important ! Keep it at the top.
      - ide
      - browser
      - system_general
      - web_dev_essential
      - web_dev_tools
#      - tracker    # uncomment to install oDesk and Elance trackers
      - tweak
