---
- name: ensure web dev tools are installed
  apt: pkg="{{ item }}" state=latest
  with_items:
    - virtualbox
    - meld
    - wireshark
    - gcolor2
  sudo: yes


- name: Download Vagrant
  shell: aria2c -c -x 10 -s {{ downloadThreads }} https://dl.bintray.com/mitchellh/vagrant/vagrant_{{ vVagrant }}_x86_64.deb chdir={{ downloadDir }} creates=vagrant_{{ vVagrant }}_x86_64.deb

- name: Install Vagrant
  apt: deb={{ downloadDir }}/vagrant_{{ vVagrant }}_x86_64.deb
  sudo: yes


- name: Download MySQL Workbench
  shell: axel -n {{ downloadThreads }} http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-{{ vMySQLWB }}-amd64.deb chdir={{ downloadDir }} creates=mysql-workbench-community-{{ vMySQLWB }}-amd64.deb

- name: Install MySQL Workbench
  apt: deb={{ downloadDir }}/mysql-workbench-community-{{ vMySQLWB }}-amd64.deb
  sudo: yes
