---
- name: add PPA repos
  apt_repository: repo="{{ item }}" update_cache=yes
  with_items:
    - ppa:webupd8team/atom
    - ppa:webupd8team/sublime-text-3
  sudo: yes

- name: Update caches after PPA being added
  apt: update_cache=yes
  sudo: yes

- name : install IDEs from PPAs
  apt: name="{{ item }}" state=present
  with_items:
    - atom
    - sublime-text-installer
  sudo: yes


- name: Download PhpStorm
  shell: axel -n {{ downloadThreads }} http://download.jetbrains.com/webide/PhpStorm-{{ vPhpStorm }}.tar.gz chdir={{ downloadDir }} creates=PhpStorm-{{ vPhpStorm }}.tar.gz

- name: Install PhpStorm
  shell: mkdir -p {{ installDir }}/PhpStorm-{{ vPhpStorm }} && tar -xf {{ downloadDir }}/PhpStorm-{{ vPhpStorm }}.tar.gz -C {{ installDir }}/PhpStorm-{{ vPhpStorm }} --strip-components=1 creates={{ installDir }}/PhpStorm-{{ vPhpStorm }}



- name: Download PyCharm
  shell: axel -n {{ downloadThreads }} http://download.jetbrains.com/python/pycharm-community-{{ vPyCharm }}.tar.gz chdir={{ downloadDir }} creates=pycharm-community-{{ vPyCharm }}.tar.gz

- name: Install PyCharm
  shell: mkdir -p {{ installDir }}/pycharm-community-{{ vPyCharm }} && tar -xf {{ downloadDir }}/pycharm-community-{{ vPyCharm }}.tar.gz -C {{ installDir }}/pycharm-community-{{ vPyCharm }} --strip-components=1 creates={{ installDir }}/pycharm-community-{{ vPyCharm }}
